// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FraudAnalyticsRequest.proto

package com.hippotech.fraud;

public final class FraudAnalyticsRequestOuterClass {
  private FraudAnalyticsRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hippotech_fraud_FraudAnalyticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hippotech_fraud_FraudAnalyticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hippotech_fraud_FraudAnalyticsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hippotech_fraud_FraudAnalyticsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033FraudAnalyticsRequest.proto\022\023com.hippo" +
      "tech.fraud\"?\n\025FraudAnalyticsRequest\022\022\n\nf" +
      "amilyName\030\001 \001(\t\022\022\n\ncardNumber\030\002 \001(\t\"=\n\026F" +
      "raudAnalyticsResponse\022\022\n\nsuspicious\030\001 \001(" +
      "\010\022\017\n\007message\030\002 \001(\t2\201\001\n\025FraudAnalyticsSer" +
      "vice\022h\n\rfraudAnalysis\022*.com.hippotech.fr" +
      "aud.FraudAnalyticsRequest\032+.com.hippotec" +
      "h.fraud.FraudAnalyticsResponseB\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hippotech_fraud_FraudAnalyticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hippotech_fraud_FraudAnalyticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hippotech_fraud_FraudAnalyticsRequest_descriptor,
        new java.lang.String[] { "FamilyName", "CardNumber", });
    internal_static_com_hippotech_fraud_FraudAnalyticsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hippotech_fraud_FraudAnalyticsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hippotech_fraud_FraudAnalyticsResponse_descriptor,
        new java.lang.String[] { "Suspicious", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
