// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FraudAnalyticsRequest.proto

package com.hippotech.fraud;

public interface FraudAnalyticsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hippotech.fraud.FraudAnalyticsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool suspicious = 1;</code>
   */
  boolean getSuspicious();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
