// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FraudAnalyticsRequest.proto

package com.hippotech.fraud;

public interface FraudAnalyticsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hippotech.fraud.FraudAnalyticsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string familyName = 1;</code>
   */
  java.lang.String getFamilyName();
  /**
   * <code>string familyName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFamilyNameBytes();

  /**
   * <code>string cardNumber = 2;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string cardNumber = 2;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();
}
